server:
  port: 8080

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

user.service:
  base.path: /v1/users
  login.path: /v1/users/login
  session.expiration.time: 864000000
  authorization:
    token.prefix: Bearer
    header.string: Authorization
    token.secret: jf9i4jgu83nfl0

baseURI: http://localhost
basePath: v1